name: Build for Android, Linux Desktop

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'
          architecture: x64 # optional, x64 or arm64
      - name: Fetch dependencies
        run: flutter pub get
      - run: flutter test
      - run: |
          flutter build apk
          cp build/app/outputs/flutter-apk/app-release.apk ./_artifact_android.apk
      - name: Prepare for building for Linux Desktop
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - name: Build for Linux Desktop
        run: |
          flutter config --enable-linux-desktop
          flutter build linux
          zip -r _artifact_linux.zip /home/ntonee/projects/zveno_frontend_all/build/linux/x64/release/bundle
      - uses: actions/upload-artifact@v3
        with:
          name: linux-bundle.zip
          path: _artifact_linux.zip
      - uses: actions/upload-artifact@v3
        with:
          name: android.apk
          path: _artifact_android.apk
      
